fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /
    
profile:
    resource: "@ProfileBundle/Resources/config/routing.xml"
    prefix:   /profile

workflow:
    resource: "@WorkflowBundle/Resources/config/routing.xml"
    prefix:   /workflow