profile:
    resource: "@ProfileBundle/Resources/config/routing.xml"
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /profile
    
workflow:
    resource: "@WorkflowBundle/Resources/config/routing.xml"
    prefix:   /workflow
    
