wise_profile:
    resource: "@WiseProfileBundle/Controller/"
    type:     annotation
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /profile